#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HoneywellScannerXamarin.Resource", IsApplication=true)]

namespace HoneywellScannerXamarin
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Honeywell.AIDC.CrossPlatform.Resource.Drawable.barcode_example_icon = global::HoneywellScannerXamarin.Resource.Drawable.barcode_example_icon;
			global::Honeywell.AIDC.CrossPlatform.Resource.Drawable.ic_launcher = global::HoneywellScannerXamarin.Resource.Drawable.ic_launcher;
			global::Honeywell.AIDC.CrossPlatform.Resource.String.ApplicationName = global::HoneywellScannerXamarin.Resource.String.ApplicationName;
			global::Honeywell.AIDC.CrossPlatform.Resource.String.Hello = global::HoneywellScannerXamarin.Resource.String.Hello;
			global::Honeywell.AIDC.CrossPlatform.Resource.String.app_name = global::HoneywellScannerXamarin.Resource.String.app_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int barcode_example_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int ic_launcher = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050007
			public const int btnScannerIntent = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int btnScannerXamarin = 2131034118;
			
			// aapt resource value: 0x7f050004
			public const int btnStartAPI = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int btnStartIntent = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int btnStopAPI = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int btnStopIntent = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int textView1 = 2131034113;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BarcodeReaderIN = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int BarcoderReaderXM = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainActivity = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int app_name = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
